steps:
# Install node packages
- name: node:10.16.3
  entrypoint: npm
  args: ['install']
  dir: 'front-end'
  timeout: "300s"
# Build productive files
- name: node:10.16.3
  entrypoint: npm
  args: ['run','ng', '--', 'build','--prod', '--aot']
  dir: 'front-end'
  timeout: "300s"
# Deploy to google cloud app engine
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: 'front-end'
  timeout: "600s"
