apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendflex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendflex
  template:
    metadata:
      labels:
        app: frontendflex
    spec:
      containers:
      - name: frontendflex-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/$GCLOUD_PROJECT/frontendflex-container:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"